#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDnn_EHaml.MyDnn_EHaml_Register.DataClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EHamlDB")]
	public partial class RegisterDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMyDnn_EHaml_User(MyDnn_EHaml_User instance);
    partial void UpdateMyDnn_EHaml_User(MyDnn_EHaml_User instance);
    partial void DeleteMyDnn_EHaml_User(MyDnn_EHaml_User instance);
    #endregion
		
		public RegisterDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EHamlDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RegisterDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RegisterDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RegisterDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RegisterDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MyDnn_EHaml_User> MyDnn_EHaml_Users
		{
			get
			{
				return this.GetTable<MyDnn_EHaml_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyDnn_EHaml_User")]
	public partial class MyDnn_EHaml_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _PortalUserId;
		
		private System.Nullable<char> _PersonalityType;
		
		private System.Nullable<char> _Type;
		
		private string _Company;
		
		private string _ActivityField;
		
		private bool _IsApprove;
		
		private string _AppCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPortalUserIdChanging(System.Nullable<int> value);
    partial void OnPortalUserIdChanged();
    partial void OnPersonalityTypeChanging(System.Nullable<char> value);
    partial void OnPersonalityTypeChanged();
    partial void OnTypeChanging(System.Nullable<char> value);
    partial void OnTypeChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnActivityFieldChanging(string value);
    partial void OnActivityFieldChanged();
    partial void OnIsApproveChanging(bool value);
    partial void OnIsApproveChanged();
    partial void OnAppCodeChanging(string value);
    partial void OnAppCodeChanged();
    #endregion
		
		public MyDnn_EHaml_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalUserId", DbType="Int")]
		public System.Nullable<int> PortalUserId
		{
			get
			{
				return this._PortalUserId;
			}
			set
			{
				if ((this._PortalUserId != value))
				{
					this.OnPortalUserIdChanging(value);
					this.SendPropertyChanging();
					this._PortalUserId = value;
					this.SendPropertyChanged("PortalUserId");
					this.OnPortalUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalityType", DbType="Char(1)")]
		public System.Nullable<char> PersonalityType
		{
			get
			{
				return this._PersonalityType;
			}
			set
			{
				if ((this._PersonalityType != value))
				{
					this.OnPersonalityTypeChanging(value);
					this.SendPropertyChanging();
					this._PersonalityType = value;
					this.SendPropertyChanged("PersonalityType");
					this.OnPersonalityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Char(1)")]
		public System.Nullable<char> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(MAX)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityField", DbType="NVarChar(MAX)")]
		public string ActivityField
		{
			get
			{
				return this._ActivityField;
			}
			set
			{
				if ((this._ActivityField != value))
				{
					this.OnActivityFieldChanging(value);
					this.SendPropertyChanging();
					this._ActivityField = value;
					this.SendPropertyChanged("ActivityField");
					this.OnActivityFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApprove", DbType="Bit NOT NULL")]
		public bool IsApprove
		{
			get
			{
				return this._IsApprove;
			}
			set
			{
				if ((this._IsApprove != value))
				{
					this.OnIsApproveChanging(value);
					this.SendPropertyChanging();
					this._IsApprove = value;
					this.SendPropertyChanged("IsApprove");
					this.OnIsApproveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppCode", DbType="NVarChar(100)")]
		public string AppCode
		{
			get
			{
				return this._AppCode;
			}
			set
			{
				if ((this._AppCode != value))
				{
					this.OnAppCodeChanging(value);
					this.SendPropertyChanging();
					this._AppCode = value;
					this.SendPropertyChanged("AppCode");
					this.OnAppCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
